spring:
  batch:
    jdbc:
      initialize-schema: always

datasource:
  default:
    hikari-maximum-pool-size: 5
    hikari-minimum-idle: 5
    hikari-connection-timeout: 3000
    jpa-show-sql: false
    jpa-open-in-view: false
    jpa-hibernate-ddl-auto: validate
  demo:
    host: localhost
    database: demo
    port: 3306
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate-dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    parameter: useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&cacheDefaultTimezone=false&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
    jdbc-url: jdbc:mysql://${datasource.demo.host}:${datasource.demo.port}/${datasource.demo.database}?${datasource.demo.parameter}